### ISSUE TITLE
docker_builder.sh execute error

### ISSUE THREAD

**Issue by Tiryoh** [rnanosaur/nanosaur_perception#13]
docker_builder.sh shows the following error.

```
Starting >>> isaac_ros_argus_camera_mono
--- stderr: isaac_ros_argus_camera_mono
/opt/isaac_ros_ws/src/isaac_ros_argus_camera/isaac_ros_argus_camera_mono/src/argus_camera_mono_node.cpp:17:10: fatal error: Argus/Argus.h: No such file or directory
 #include <Argus/Argus.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/monocular_node.dir/src/argus_camera_mono_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/monocular_node.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< isaac_ros_argus_camera_mono [14.7s, exited with code 2]
```

Executing [fix_jetson_docker.sh](https://github.com/rbonghi/isaac_ros_tutorial/blob/main/scripts/fix_jetson_docker.sh) solved this problem.
Maybe this docker patch process can be included in the [nanosaur installation script](https://github.com/rnanosaur/nanosaur/blob/master/nanosaur/scripts/nanosaur ).

## Environment

Jetson Nano 4GB + JetPack 4.6

## To Reproduce

1. Install JetPack 4.6
2. Run `sudo apt update && sudo apt -y full-upgrade && sudo apt -y autoremove && sudo apt -y install curl`
3. Run `curl https://raw.githubusercontent.com/rnanosaur/nanosaur/master/nanosaur/scripts/nanosaur -o $HOME/nanosaur && chmod +x $HOME/nanosaur && $HOME/nanosaur install dev`
4. Run `cd ~/nanosaur_perception/src/nanosaur_perception && bash nanosaur_perception/scripts/docker_builder.sh`

**Comment by rbonghi** [comment]
Hi @Tiryoh , always thank you

On nanosaur there is a private repo https://github.com/rnanosaur/nanosaur-jetson-runner (now public) only to manage the remote build and the installation on my local jetson.

I think, more than add on the installation script, I will add a note on the wiki readme :-)

**Comment by Tiryoh** [comment]
> On nanosaur there is a private repo https://github.com/rnanosaur/nanosaur-jetson-runner (now public) only to manage the remote build and the installation on my local jetson.

Wow! This is awesome! I'll try it.

> I think, more than add on the installation script, I will add a note on the wiki readme :-)

Thanks, It sounds reasonable. I guess people who build their own docker image are "developers", so I think it is enough to be written in the wiki so they can handle it.

**Comment by rbonghi** [comment]
Fixed https://github.com/rnanosaur/nanosaur/wiki/Build-docker
